import type { Metadata } from "next";
import { Manrope, Wix_Madefor_Display } from "next/font/google";
import "./globals.css";

const wixSans = Wix_Madefor_Display({
  variable: "--font-wix-sans",
  subsets: ["latin"],
});

const manropeSans = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WorkNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${wixSans.variable} ${manropeSans.variable} font-text antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
